import type { Metadata } from 'next';
import {
  Archivo,
  Archivo_Black,
  Archivo_Narrow,
  Cormorant_Garamond,
  IBM_Plex_Mono
} from 'next/font/google';
import './globals.scss';
import SmoothScroll from '@/components/common/SmoothScroll';

const archivo = Archivo({
  subsets: ['latin'],
  variable: '--font-archivo',
  display: 'swap'
});

const archivoBlack = Archivo_Black({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-archivo-black',
  display: 'swap'
});

const archivoNarrow = Archivo_Narrow({
  subsets: ['latin'],
  variable: '--font-archivo-narrow',
  display: 'swap'
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ['500'],
  subsets: ['latin'],
  variable: '--font-ibm-plex-mono',
  display: 'swap'
});

// Only the italic is used: it's the accent voice in headlines and copy.
const cormorantGaramond = Cormorant_Garamond({
  weight: '400',
  style: 'italic',
  subsets: ['latin'],
  variable: '--font-cormorant-garamond',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

// The document and its fonts. The site's pages sit in (site), which adds
// the navbar and the footer; the share link pages in (share) go without.
export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${archivo.variable} ${archivoBlack.variable} ${archivoNarrow.variable} ${ibmPlexMono.variable} ${cormorantGaramond.variable}`}
    >
      <body>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
