import type { Metadata } from 'next';
import './globals.scss';
import SmoothScroll from '@/components/common/SmoothScroll';
import { SiteScrollbar } from '@/components/layout/SiteScrollbar';
import { SITE_URL } from '@/lib/site/url';
import { fontVariables } from './fonts';

// The title and description wait for the client's wording (the copy
// sheet). The base address makes the link previews' images absolute.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: { siteName: 'Candy Heist', type: 'website' },
  twitter: { card: 'summary_large_image' }
};

// The document, its fonts and its scrolling (Lenis, and the site's own
// scrollbar). The site's pages sit in (site), which adds the navbar and
// the footer; the share link pages in (share) go without.
export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={fontVariables}>
      <body>
        <SmoothScroll>
          {children}
          <SiteScrollbar />
        </SmoothScroll>
      </body>
    </html>
  );
}
