import type { Metadata } from 'next';
import './globals.scss';
import SmoothScroll from '@/components/common/SmoothScroll';
import { SiteScrollbar } from '@/components/layout/SiteScrollbar';
import { fontVariables } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

// The document, its fonts and its scrolling (Lenis, and the site's own
// scrollbar). The site's pages sit in (site), which adds the navbar and
// the footer; the share link pages in (share) go without.
export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={fontVariables}>
      <body>
        <SmoothScroll>
          {children}
          <SiteScrollbar />
        </SmoothScroll>
      </body>
    </html>
  );
}
